# Copyright (C) 2017  ParadoxSpiral
#
# This file is part of parabot.
#
# Parabot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Parabot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Parabot.  If not, see <http://www.gnu.org/licenses/>.


[package]
name = "parabot"
version = "0.1.0"
authors = ["ParadoxSpiral <ParadoxSpiral@riseup.net>"]

[dependencies]
crossbeam = "0.2"
hyper = "0.11"
irc = "0.12"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
threadpool = "1.3"
slog = "2.0"
slog-async = "2.0"
slog-term = "2.0"
toml = "0.4"