# Copyright (C) 2017  ParadoxSpiral
#
# This file is part of parabot.
#
# Parabot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Parabot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Parabot.  If not, see <http://www.gnu.org/licenses/>.


[package]
name = "parabot"
version = "0.1.0"
authors = ["ParadoxSpiral <ParadoxSpiral@riseup.net>"]

[dependencies]
chrono = "0.4"
crossbeam = "0.2"
diesel = { version = "0.13.0", features = ["sqlite"] }
diesel_codegen = { version = "0.13.0", features = ["sqlite"] }
irc = "0.12"
lazy_static = "0.2"
parking_lot = {version = "0.4", features = ["nightly"]}
regex = "0.2"
reqwest = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
threadpool = "1.3"
slog = { version = "2.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-async = "2.0"
slog-term = "2.0"
toml = "0.4"
unicode-segmentation = "1.2"

[dependencies.forecast]
git = "https://github.com/ParadoxSpiral/forecast-rs"