[package]
name = "parabot"
version = "1.0.0"
authors = ["Jonathan Schleußer <ParadoxSpiral@riseup.net>"]

[dependencies]
parabot-core = {version = "*", path = "parabot-core"}
shellexpand = "1"
tokio = "0.1"

[profile.release]
lto = true
opt-level = 3
