[[server]]
address = "irc.rizon.net"
nickname = "parabot"
# optional: alternative_nicknames = ["weebot"]
nickserv_password = "test123"
# optional: server_password = "test123"
database = "parabot_empty.db" # Different servers may populate the same db
# optional: weather_api_secret = "secret" a https://darksky.net API secret
# optional: geocoding_api_key = "key" a https://developer.mapquest.com API key
# optional: max_burst_messages = 4
# optional: burst_window_length = 8 # Time between bursts in seconds
port = 6697
	[[server.channel]]
	name = "#c"
	# optional: password = "channel_key"
	# optional: url_blacklisted_domains = ["google.com"]
	modules = ["duckduckgo", "url-info", "tell", "weather"]
	[[server.channel]]
	name = "#news"
	modules = ["url-info", "weather"]

[[server]]
address = "irc.freenode.net"
nickname = "parabot"
nickserv_password = "test123"
port = 6697
	[[server.channel]]
	name = "##rust"
	modules = ["url-info"]