[[server]]
nickname = "parabot"
#optional: alternative_nicknames = ["weebot"]
nickserv_password = "test123"
# optional: server_password = "test123"
address = "irc.rizon.net"
port = 6697
	[[server.channel]]
	name = "#c"
	#optional: password = "channel_key"
	modules = ["url", "tell", "weather", "wolfram-alpha"]
	[[server.channel]]
	name = "#news"
	modules = ["url", "weather"]

[[server]]
nickname = "parabot"
nickserv_password = "test123"
address = "irc.freenode.net"
port = 6697
	[[server.channel]]
	name = "##rust"
	modules = ["url"]