[[server]]
address = "irc.rizon.net"
nickname = "parabot"
#optional: alternative_nicknames = ["weebot"]
nickserv_password = "test123"
# optional: server_password = "test123"
database = "parabot_empty.db" # Needs actual URL, different servers may populate the same db
# optional: weather_api_secret = "secret" a https://darksky.net API secret
port = 6697
	[[server.channel]]
	name = "#c"
	#optional: password = "channel_key"
	modules = ["url", "tell", "weather", "wolfram-alpha"]
	[[server.channel]]
	name = "#news"
	modules = ["url", "weather"]

[[server]]
address = "irc.freenode.net"
nickname = "parabot"
nickserv_password = "test123"
port = 6697
	[[server.channel]]
	name = "##rust"
	modules = ["url"]